---
- name: Add repository-gpg-key for fastd
  apt_key: "keyserver={{ pgp_keyserver }} id={{ fastd_repository_key }}"

- name: add universe-factory repository for fastd
  apt_repository: repo="{{ item }}" update_cache=yes
  with_items:
  - 'deb http://repo.universe-factory.net/debian/ sid main'

- name: install fastd
  apt: name=fastd state=present

- name: fastd directories
  file: path="/etc/fastd/{{ fastd_interface }}" state=directory

- name: fastd.conf
  template: >
    src=fastd.conf.j2
    dest="/etc/fastd/{{ fastd_interface }}/fastd.conf"
    owner=root
    group=root
    mode='0600'
  notify: 
  - restart fastd

- name: Create secret-file
  shell: echo "secret \"$(fastd --generate-key --machine-readable)\";" > /etc/fastd/{{ fastd_interface }}/secret && chmod 600 /etc/fastd/{{ fastd_interface }}/secret
  args:
    creates: "/etc/fastd/{{ fastd_interface }}/secret"

- name: Update fastd secret (if defined)
  when: fastd_secret != 'generate'
  lineinfile: dest=/etc/fastd/{{ fastd_interface }}/secret regexp='^secret' line='secret "{{ fastd_secret }}";'
  notify:
  - restart fastd

- name: Create fastd peer directory
  file: path=/etc/fastd/{{ fastd_interface }}/peers state=directory

- name: Verify configuration
  shell: fastd --verify-config -c /etc/fastd/{{ fastd_interface }}/fastd.conf

